sonar.projectKey=Ineees24_skillhub2
sonar.organization=ineees24
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

sonar.sources=skillhub-back/app,skillhub-back/routes,skillhub-back/bootstrap,skillhub-back/config,skillhub-back/database,skillhub-front/src
sonar.tests=skillhub-back/tests,skillhub-front/src

sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/build/**,**/storage/**,**/bootstrap/cache/**,skillhub-back/public/**

sonar.coverage.exclusions=\
  **/database/migrations/**, \
  **/database/seeders/**, \
  **/database/factories/**, \
  **/bootstrap/**, \
  **/config/**, \
  **/routes/**, \
  skillhub-front/src/assets/**, \
  skillhub-front/src/components/**, \
  skillhub-front/src/contexts/**, \
  skillhub-front/src/data/**, \
  skillhub-front/src/pages/**, \
  skillhub-front/src/styles/**, \
  skillhub-front/src/App.css, \
  skillhub-front/src/index.css, \
  skillhub-front/src/main.jsx, \
  skillhub-front/src/App.jsx

sonar.test.inclusions=skillhub-back/tests/**/*.php,skillhub-front/src/**/*.test.js,skillhub-front/src/**/*Test.js
sonar.javascript.lcov.reportPaths=skillhub-front/coverage/lcov.info
sonar.php.coverage.reportPaths=skillhub-back/coverage/clover.xml